# Form implementation generated from reading ui file 'design/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class MainWindowDesign(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 577)
        MainWindow.setStyleSheet("""
color: black;
""")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 891, 551))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.login = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.login.setStyleSheet("QLineEdit {\n"
"    background: #FFFFFF;\n"
"    border-radius: 15px;\n"
"    padding-left: 5px;\n"
"}")
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 0, 0, 1, 2)
        self.password = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.password.setStyleSheet("QLineEdit {\n"
"    background: #FFFFFF;\n"
"    border-radius: 15px;\n"
"    padding-left: 5px;\n"
"}")
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.login.setFixedHeight(50)
        self.password.setFixedHeight(50)
        self.gridLayout.addWidget(self.password, 1, 0, 1, 2)
        self.sing_in = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.sing_in.setObjectName("sing_in")
        self.gridLayout.addWidget(self.sing_in, 2, 0, 1, 1)
        self.create_account = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.create_account.setObjectName("create_account")
        self.gridLayout.addWidget(self.create_account, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.layoutWidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 887, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuAuthorization = QtWidgets.QMenu(parent=self.menuBar)
        self.menuAuthorization.setObjectName("menuAuthorization")
        MainWindow.setMenuBar(self.menuBar)
        self.sing_in_menubar = QtGui.QAction(parent=MainWindow)
        self.sing_in_menubar.setObjectName("sing_in_menubar")
        self.create_account_menubar = QtGui.QAction(parent=MainWindow)
        self.create_account_menubar.setObjectName("create_account_menubar")
        self.menuAuthorization.addAction(self.sing_in_menubar)
        self.menuAuthorization.addAction(self.create_account_menubar)
        self.menuBar.addAction(self.menuAuthorization.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Register"))
        self.login.setPlaceholderText(_translate("MainWindow", "Login"))
        self.password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.sing_in.setText(_translate("MainWindow", "Sing in"))
        self.create_account.setText(_translate("MainWindow", "Create account"))
        self.menuAuthorization.setTitle(_translate("MainWindow", "Authorization"))
        self.sing_in_menubar.setText(_translate("MainWindow", "Sing in"))
        self.create_account_menubar.setText(_translate("MainWindow", "Create account"))
